[package]
name = "aboboo"
version = "0.1.0"
edition = "2021"

[lib]
name = "aboboo_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "aboboo"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-fs = "2"
tauri-plugin-dialog = "2"
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4"] }
